app_personlikeproduct:
    resource: "@AppBundle/Resources/config/routing/personlikeproduct.yml"
    prefix:   /personlikeproduct

app_product:
    resource: "@AppBundle/Resources/config/routing/product.yml"
    prefix:   /product

app_person:
    resource: "@AppBundle/Resources/config/routing/person.yml"
    prefix:   /person


