<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function findLikeName($name)
    {
        $qb = $this->createQueryBuilder('p');
        $results = $qb->where(
                 $qb->expr()->like('p.fName', ':name')
             )
             ->setParameter(':name','%'.$name.'%')
             ->getQuery()
             ->getResult();
        
        return $results;
    }
}
