<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findLikeName($name)
    {
        $qb = $this->createQueryBuilder('p');
        $results = $qb->where(
                 $qb->expr()->like('p.name', ':name')
             )
             ->setParameter(':name','%'.$name.'%')
             ->getQuery()
             ->getResult();
        
        return $results;
    }
}
